# Scoring weights
vector_weight: 0.7
keyword_weight: 0.3

# Score thresholds
min_vector_score: 0.475
min_keyword_score: 0.1
min_combined_score: 0.475

# Exact match thresholds
exact_match_min_vector_score: 0.95
exact_match_min_keyword_score: 0.9

# Search optimization parameters
initial_candidates: 100
max_candidates: 500
candidate_expansion_threshold: 0.5

# Reranking configuration
enable_reranking: true